name: Run GALL.mjs script

on:
  schedule:
    - cron: '0 16 * * *'  # 每天中国时区0点运行（注意：使用的是UTC时间）
  workflow_dispatch:  # 手动触发工作流

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.9'

      - name: Run gall.mjs script
        run: |
          node GALL.mjs

      - name: Get number of lines in GAll.txt
        id: get_lines
        run: |
          lines=$(wc -l < GAll.txt)
          echo "lines=$lines" >> $GITHUB_ENV

      - name: Get current date and time in Beijing
        id: get_datetime
        run: |
          current_datetime=$(TZ="Asia/Shanghai" date "+%Y-%m-%d %H:%M")
          echo "current_datetime=$current_datetime" >> $GITHUB_ENV

      - name: Commit and push result
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          
          # 创建推送消息
          message="更新 ${lines} 个节点 (${{ env.current_datetime }})"
          
          # 添加修改、提交并推送
          git add GAll.txt
          git commit -m "$message" || echo "No changes to commit"
          git push origin HEAD:main
